#!/bin/bash

#
#   This file is part of Filu.
#
#   Copyright (C) 2007, 2010, 2011, 2012, 2013 loh.tar@googlemail.com
#
#   Filu is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 2 of the License, or
#   (at your option) any later version.
#
#   Filu is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with Filu. If not, see <http:#www.gnu.org/licenses/>.
#

source install-include-functions.sh

checkSystem "apt-get" "Debian"
checkIfRoot
startRolex "Run apt-get"

apt-get --yes install       \
  build-essential           \
  cmake                     \
  libqt4-dev                \
  libqt4-sql                \
  libqt4-sql-psql           \
  libpq-dev                 \
  libmuparser-dev           \
  libcache-cache-perl       \
  libdate-simple-perl       \
  libio-html-perl           \
  libtimedate-perl          \
  libwww-perl               \
  libxml-libxml-simple-perl \
  libhtml-tableextract-perl \
  postgresql

checkPoint "(Most) Dependencies installed by apt-get" "Fetch TA-Lib"
#
# Install TA-Lib must be done this way after other dependencies or it will fail
#
# Don't download if already installed
# http://stackoverflow.com/a/18341822
if [ $(dpkg-query -l | grep ta-lib0-dev | wc -l) -eq 0 ]
then
  wget -P /tmp \
    http://www.zwets.com/debs/unstable/ta-lib0-dev_0.4.0-2_i386.deb \
    http://www.zwets.com/debs/unstable/libta-lib0_0.4.0-2_i386.deb

  checkPoint "TA-Lib downloaded" "Install TA-Lib"

  dpkg -i \
    /tmp/ta-lib0-dev_0.4.0-2_i386.deb \
    /tmp/libta-lib0_0.4.0-2_i386.deb

  checkPoint "TA-Lib installed" "Run cmake .."

else
  true
  checkPoint "Nice. TA-Lib already installed" "Run cmake .."
fi 

finishInstall
