#!/bin/bash

#
#   This file is part of Filu.
#
#   Copyright (C) 2007, 2010, 2011, 2012, 2013 loh.tar@googlemail.com
#
#   Filu is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 2 of the License, or
#   (at your option) any later version.
#
#   Filu is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with Filu. If not, see <http:#www.gnu.org/licenses/>.
#

source install-include-functions.sh

checkSystem "yum" ".rpm"
checkIfRoot
startRolex "Run yum"

yum -y install              \
  gcc-c++                   \
  cmake                     \
  qt-devel                  \
  qt-postgresql             \
  postgresql-devel          \
  muParser-devel            \
  postgresql                \
  postgresql-server         \
  perl-libwww-perl          \
  perl-Cache-Cache          \
  perl-Date-Simple          \
  perl-IO-HTML              \
  perl-TimeDate             \
  perl-HTML-TableExtract
#  perl-XML-LibXML-Simple

checkPoint "(Most) Dependencies installed" "Test if perl-XML-LibXML-Simple is available"

if ! yum list perl-XML-LibXML-Simple > /dev/null 2> /dev/null
then
  true
  checkPoint "No! It's not" "Will install via App-cpanminus"
  yum -y install perl-App-cpanminus libxml2-devel
  checkPoint "App-cpanminus installed" "Run cpanm XML::LibXML::Simple"
  cpanm XML::LibXML::Simple --notest

else
  checkPoint "Nice! Yes it is" "Run yum"
  yum -y install perl-XML-LibXML-Simple
fi

checkPoint "perl-XML-LibXML-Simple installed" "Test if TA-Lib is available"

if ! yum list ta-lib > /dev/null 2> /dev/null
then
  checkPoint "No! It's not" "Test machine type"
  machineType=`uname -m`
  if [ ${machineType} == 'x86_64' ]; then
    checkPoint "It's x86_64" "Run yum to install package from 'rpm-sphere'"
    yum -y install \
      http://download.opensuse.org/repositories/home:/zhonghuaren/Fedora_19/x86_64/ta-lib-0.4.0-2.1.x86_64.rpm \
      http://download.opensuse.org/repositories/home:/zhonghuaren/Fedora_19/x86_64/ta-lib-devel-0.4.0-2.1.x86_64.rpm

  elif [ ${machineType} == 'i686' ]; then
    checkPoint "It's i686" "Run yum to install package from 'rpm-sphere'"
    yum -y install \
      http://download.opensuse.org/repositories/home:/zhonghuaren/Fedora_19/i686/ta-lib-0.4.0-2.1.i686.rpm \
      http://download.opensuse.org/repositories/home:/zhonghuaren/Fedora_19/i686/ta-lib-devel-0.4.0-2.1.i686.rpm

  else
    exitError "Cool! You are using ${machineType} but sadly I can't go on now." \
              "Install TA-Lib from some other repo or source"
  fi

else
  true
  checkPoint "Nice! Yes it is" "Run yum"
  yum -y install ta-lib
fi

checkPoint "TA-Lib installed" "Run cmake .."

finishInstall
