#!/bin/bash

# http://stackoverflow.com/a/4785518
if ! command -v yum >/dev/null 2>&1
then
  echo "This looks not like a .rpm system (found no yum)"
  exit 1
fi

red="\e[1;31m"
cyan="\e[0;36m"
noColor="\e[0m"
colorStar="${cyan}*${noColor}"
talibRepo="\
[rpm-sphere]
name=RPM Sphere
baseurl=http://download.opensuse.org/repositories/home:/zhonghuaren/Fedora_19/
gpgkey=http://download.opensuse.org/repositories/home:/zhonghuaren/Fedora_19/repodata/repomd.xml.key
enabled=1
gpgcheck=1"

checkPoint()
{
  if [ $? -ne 0 ]; then
    echo -e "${red}*** Error ***${noColor} Something went wrong :-("
    exit 1
  else
    echo -e "${colorStar}"
    echo -e "${cyan}*  OK:${noColor}   $1"
    echo -e "${cyan}*  Next:${noColor} $2"
    echo -e "${colorStar}"
    sleep 1s
  fi
}

checkPoint "Let's go!" "Test if TA-Lib is available"
# Time measuring taken from Arch Wiki, thanks guys
# https://wiki.archlinux.org/index.php/Full_System_Backup_with_rsync
START=$(date +%s)

#checkPoint "" "Run apt-get"
# Test for TA-Lib
if ! yum list  ta-lib > /dev/null 2> /dev/null
then
	checkPoint "No! It's not" "Add repository 'rpm-sphere'"
	su -c "echo '$talibRepo' > /etc/yum.repos.d/rpm-sphere.repo"
	checkPoint "Repository added" "Run yum"
else
  true
  checkPoint "Nice! Yes it is" "Run yum"
fi

checkPoint "Run yum"
su -c "yum install  \
gcc-c++ \
cmake  \
qt-devel  \
ta-lib-devel \
muParser-devel  \
perl-Cache-Cache \
perl-Date-Simple \
perl-IO-HTML \
perl-TimeDate \
perl-XML-Simple \
perl-HTML-TableExtract \
qt-postgresql \
postgresql \
postgresql-server \
postgresql-devel
"

#- libpqxx
# - libqt4-sql \
# - libqt4-sql-psql \
# - libpq-dev \
# - libwww-perl \


if [ ! -d build ]; then mkdir build; fi
cd build
cmake ..
checkPoint "CMake configured" "Compile programs"
make
checkPoint "Filu programs compiled" "Install programs"
sudo make install
checkPoint "Filu programs installed" "Configure PostgreSQL"
sudo ldconfig
cd ..
sudo filu-cfg-postgresql
checkPoint "PostgreSQL configured" "Stop my Rolex"

FINISH=$(date +%s)
echo -e "${colorStar}"
echo -e "${colorStar}  Total install time: $(( ($FINISH-$START) / 60 )) minutes, $(( ($FINISH-$START) % 60 )) seconds"
echo -e "${colorStar}"
echo -e "${colorStar}  Filu is ready to use :-)"
echo -e "${colorStar}  Take a look at your application menu below 'Office' for PerformerF, ManagerF and InspectorF"
echo -e "${colorStar}  I suggest now to run 'agentf doc first'"
echo -e "${colorStar}"
